import httpStatus from "http-status";
import AppError from "../../utils/AppError";
import { Company } from "./companies.model";
import { ObjectId } from "mongoose";
import { TCompany } from "./companies.interface";

// ------------------ validate company business rules ------------------
/**
 *
 * @param payload New company creation data
 * @param creatorUserId who created the company (owner)
 * @returns true if valid, throws AppError if invalid
 */
export const validateCompanyBusinessRules = (
  payload: TCompany,
  creatorUserId: string
) => {
  const { name, description, industry, website, location } = payload;

  // company name
  if (name.length < 3 || name.length > 120) {
    throw new AppError(
      httpStatus.BAD_REQUEST,
      "Company name must be between 3 and 120 characters"
    );
  }

  // prevent garbage names
  if (!/[a-zA-Z]/.test(name)) {
    throw new AppError(
      httpStatus.BAD_REQUEST,
      "Company name must contain alphabetic characters"
    );
  }

  // description
  if (description.length < 50 || description.length > 500) {
    throw new AppError(
      httpStatus.BAD_REQUEST,
      "Company description must be between 50 and 5000 characters"
    );
  }

  // basic XSS protection
  if (/<script|<\/script>|<iframe/i.test(description)) {
    throw new AppError(
      httpStatus.BAD_REQUEST,
      "Company description contains unsafe HTML"
    );
  }

  // industry
  if (industry.length < 2 || industry.length > 100) {
    throw new AppError(httpStatus.BAD_REQUEST, "Industry value is invalid");
  }

  // website
  if (website) {
    try {
      const url = new URL(website);

      // basic phishing prevention
      if (!["http:", "https:"].includes(url.protocol)) {
        throw new Error();
      }
    } catch {
      throw new AppError(httpStatus.BAD_REQUEST, "Invalid company website URL");
    }
  }

  // location consistency
  if (location?.geo) {
    const { lat, lng } = location.geo;

    if (
      typeof lat !== "number" ||
      typeof lng !== "number" ||
      lat < -90 ||
      lat > 90 ||
      lng < -180 ||
      lng > 180
    ) {
      throw new AppError(httpStatus.BAD_REQUEST, "Invalid geo coordinates");
    }
  }

  // creator sanity
  if (!creatorUserId) {
    throw new AppError(httpStatus.UNAUTHORIZED, "Company creator is required");
  }

  return true;
};

// ------------------ generate unique slug ------------------
/**
 *
 * @param baseSlug new slug generated by slugify
 * @returns unique slug
 */
export const generateUniqueSlug = async (baseSlug: string): Promise<string> => {
  // Try base slug first
  const existingBase = await Company.findOne(
    { slug: baseSlug },
    { slug: 1 }
  ).lean();

  if (!existingBase) {
    return baseSlug;
  }

  // Find all slugs starting with baseSlug-
  const regex = new RegExp(`^${baseSlug}-(\\d+)$`);

  const existingSlugs = await Company.find(
    { slug: { $regex: regex } },
    { slug: 1 }
  ).lean();

  // Extract numeric suffixes
  let maxCounter = 0;

  for (const doc of existingSlugs) {
    const match = doc.slug.match(regex);
    if (match && match[1]) {
      const counter = parseInt(match[1], 10);
      if (counter > maxCounter) {
        maxCounter = counter;
      }
    }
  }
  return `${baseSlug}-${maxCounter + 1}`;
};
