export const countryCurrencyMap: Record<string, string> = {
  // --- South Asia ---
  Bangladesh: "BDT",
  India: "INR",
  Pakistan: "PKR",
  Nepal: "NPR",
  "Sri Lanka": "LKR",
  Bhutan: "BTN",
  Maldives: "MVR",
  Afghanistan: "AFN",

  // --- East Asia ---
  China: "CNY",
  Japan: "JPY",
  SouthKorea: "KRW",
  NorthKorea: "KPW",
  Mongolia: "MNT",
  Taiwan: "TWD",
  HongKong: "HKD",
  Macau: "MOP",

  // --- Southeast Asia ---
  Singapore: "SGD",
  Malaysia: "MYR",
  Thailand: "THB",
  Indonesia: "IDR",
  Philippines: "PHP",
  Vietnam: "VND",
  Cambodia: "KHR",
  Laos: "LAK",
  Myanmar: "MMK",
  Brunei: "BND",
  EastTimor: "USD",

  // --- Middle East ---
  SaudiArabia: "SAR",
  UnitedArabEmirates: "AED",
  Qatar: "QAR",
  Kuwait: "KWD",
  Bahrain: "BHD",
  Oman: "OMR",
  Israel: "ILS",
  Jordan: "JOD",
  Lebanon: "LBP",
  Iraq: "IQD",
  Iran: "IRR",
  Turkey: "TRY",
  Yemen: "YER",

  // --- Europe ---
  Germany: "EUR",
  France: "EUR",
  Italy: "EUR",
  Spain: "EUR",
  Portugal: "EUR",
  Netherlands: "EUR",
  Belgium: "EUR",
  Austria: "EUR",
  Ireland: "EUR",
  Finland: "EUR",
  Greece: "EUR",
  Slovakia: "EUR",
  Slovenia: "EUR",
  Estonia: "EUR",
  Latvia: "EUR",
  Lithuania: "EUR",
  Luxembourg: "EUR",
  Malta: "EUR",
  Cyprus: "EUR",

  UnitedKingdom: "GBP",
  Switzerland: "CHF",
  Norway: "NOK",
  Sweden: "SEK",
  Denmark: "DKK",
  Iceland: "ISK",

  Poland: "PLN",
  CzechRepublic: "CZK",
  Hungary: "HUF",
  Romania: "RON",
  Bulgaria: "BGN",
  Croatia: "EUR",
  Serbia: "RSD",
  BosniaAndHerzegovina: "BAM",
  Albania: "ALL",
  NorthMacedonia: "MKD",
  Ukraine: "UAH",
  Russia: "RUB",
  Belarus: "BYN",
  Moldova: "MDL",

  // --- North America ---
  UnitedStates: "USD",
  Canada: "CAD",
  Mexico: "MXN",

  // --- Central America ---
  Guatemala: "GTQ",
  Honduras: "HNL",
  ElSalvador: "USD",
  Nicaragua: "NIO",
  CostaRica: "CRC",
  Panama: "USD",

  // --- Caribbean ---
  Jamaica: "JMD",
  TrinidadAndTobago: "TTD",
  Bahamas: "BSD",
  Barbados: "BBD",
  DominicanRepublic: "DOP",
  Haiti: "HTG",

  // --- South America ---
  Brazil: "BRL",
  Argentina: "ARS",
  Chile: "CLP",
  Colombia: "COP",
  Peru: "PEN",
  Bolivia: "BOB",
  Paraguay: "PYG",
  Uruguay: "UYU",
  Venezuela: "VES",
  Ecuador: "USD",

  // --- Africa ---
  SouthAfrica: "ZAR",
  Nigeria: "NGN",
  Kenya: "KES",
  Tanzania: "TZS",
  Uganda: "UGX",
  Rwanda: "RWF",
  Ethiopia: "ETB",
  Ghana: "GHS",
  Egypt: "EGP",
  Morocco: "MAD",
  Algeria: "DZD",
  Tunisia: "TND",
  Libya: "LYD",
  Sudan: "SDG",
  Senegal: "XOF",
  IvoryCoast: "XOF",
  Mali: "XOF",
  BurkinaFaso: "XOF",
  Niger: "XOF",
  Togo: "XOF",
  Benin: "XOF",
  Cameroon: "XAF",
  Chad: "XAF",
  Gabon: "XAF",
  Congo: "XAF",
  Angola: "AOA",
  Zambia: "ZMW",
  Zimbabwe: "ZWL",
  Namibia: "NAD",
  Botswana: "BWP",

  // --- Oceania ---
  Australia: "AUD",
  NewZealand: "NZD",
  PapuaNewGuinea: "PGK",
  Fiji: "FJD",
  SolomonIslands: "SBD",

  // fallback if country is not in user profile
  Unknown: "USD",
  International: "USD",
};
